### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [momower1/PointCloudEngine#14]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by momower1** [comment]
As stated in the readme this project does not have an explicit license and is therefore it is not allowed to use, distribute or change this software and the source code without my written permission. The project is currently public because it is a good way to get in touch with people that might be interested in working with me. If you just want to take a look at the source code only for your studies, that's fine by me.
